### ISSUE TITLE
Model document types

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-un#2]
* Addendum
* Communication
* Corrigendum
* Reissue (of something)
* Documents relating to agendas of principal organs
* Documents relating to programme budget implications
* Notes by the Secretary-General
* Reports of intergovernmental and expert bodies
* Resolutions and other formal decisions of United Nations organs

**Comment by ronaldtse** [comment]
Have we modeled them to close this?

**Comment by opoudjis** [comment]
Updated UML model.

The RNC grammar here will be deleted. There is already a UNECE grammar at https://github.com/riboseinc/metanorma-model-iso/tree/master/grammars, and that is where all Metanorma RNC grammars will continue to be maintained. I will not maintain the RNC grammars for Metanorma across 10 different repositories. The RNC grammar here ignores all the inheritance from the three underlying grammars unece.rnc inherits from, and therefore is unmaintainable.
