### ISSUE TITLE
Model languages: "Original", "Available in"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-model-un#5]
(http://dd.dgacm.org/editorialmanual/ed-guidelines/format/mast_cover.htm)

Language

Documents must be drafted and submitted in one of the six official languages.

The language of the document indicated in the masthead  (for example Original: English) is the language in which the text was drafted in the Secretariat or submitted to the Secretariat by a Member State or another organization for translation into the other official languages.

The language indicated in the masthead applies to the main document and not to any annexes or attachments to it. If the original language of any annex or attachment is different from that of the main document, that original language is indicated in square brackets at the top of the annex in question (under and to the right of the heading Annex). If the annex is being circulated in the language of submission only, however, it is not necessary to indicate the language notation at the top of the annex.

If a complete text is submitted in more than one language version – for example, a peace agreement drafted and signed in equally authentic English and French versions – then the language is indicated in the masthead – or above the text in the case of an annex – as Original: English and French.

If a document is made up of a number of different texts – such as replies from Member States or curricula vitae – submitted in various languages, then the language is indicated in the masthead as, for example, Original: Arabic/English/French/Spanish.

Similarly, if some sections of a report are drafted in English and some in French, the language shown is Original: English/French.

If a document is issued in one official language only, the notation Original: English is replaced with Arabic only, Chinese only, English only and the like.

If a document is issued in more than one official language but not in all of them, the languages are indicated in the masthead, below the original language:

Original: English
English, French and Spanish only
Note: A footnote may be added to indicate the reason for the issuance of the document in some languages only.

This instruction does not apply to corrigenda. For the language designation in corrigenda, see Editorial guidelines/Basic Documents/Corrigenda and reissues.

**Comment by opoudjis** [comment]
So, the model differentiates between language of submission and language of issuance. We will keep the existing language for the latter, because the default would be to assume that in bibdata it describes a publication, and allow it to have multiple values. The language of submission will be a separate attribute.

**Comment by opoudjis** [comment]
Indicating the language of annexes separately is something I'd rather leave in the too-hard basket; it's an uncomfortable conflation of metadata and content.

**Comment by opoudjis** [comment]
I'm implementing the gematriya above for the titlepage.

**Comment by ronaldtse** [comment]
I think each clause/section/block technically can support metadata like language and script; it’s supported by the document model anyway.

**Comment by opoudjis** [comment]
... It is?

**Comment by ronaldtse** [comment]
It’s supported in BasicDoc in TextElement via LocalizedString. Maybe we should allow that at the section metadata level too...?

**Comment by opoudjis** [comment]
That's what I thought. That will need to be a new ticket.
